/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import animeScene from '../assets/3d/free_-_skybox_anime_sky.glb'
import { useFrame } from '@react-three/fiber'

const AnimeSky = ({ isRotating }) => {
  const anime = useGLTF(animeScene);
  const animeRef = useRef();

  useFrame((_, delta) => {
    if (isRotating){
        animeRef.current.rotation.y += 0.15 * delta
    }
    })
  return (
    <mesh ref={animeRef} > 
    <primitive object={anime.scene}/>
    </mesh>
  );
}
//scale={800}

export default AnimeSky;