/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dobbyisthegoat (https://sketchfab.com/dobbyisthegoat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-flying-5c8c586da7ad450a8e58b56289a26739
Title: Dragon flying
*/
import { useEffect, useRef } from 'react'
import dragonScene from '../assets/3d/dragon_flying.glb';
import { useAnimations, useGLTF } from '@react-three/drei';

const Dragon = ({ isRotating, ...props }) => {
    const ref = useRef();
    const {scene, animations} = useGLTF(dragonScene);
    const { actions } = useAnimations(animations, ref);

    useEffect(() =>{
      if (isRotating){
        actions["Take 001"].play();
      } else{
        actions["Take 001"].stop();
      }
    }, [actions, isRotating])
  return (
    <mesh {...props} ref={ref}>
        <primitive object={scene}/>
    </mesh>
  )
}

export default Dragon
// import React, { useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";

// export function Model(props) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF("/dragon_flying.glb");
//   const { actions } = useAnimations(animations, group);
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
//           <group name="root">
//             <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
//               <group
//                 name="Sketchfab_model_0"
//                 rotation={[-Math.PI / 2, 0, 0]}
//                 scale={7.319}
//               >
//                 <group name="root_1">
//                   <group
//                     name="GLTF_SceneRootNode_2"
//                     rotation={[Math.PI / 2, 0, 0]}
//                   >
//                     <group name="RootNode0_0_3" scale={0.01}>
//                       <group name="skeletal3_3_4">
//                         <group name="GLTF_created_0_5">
//                           <group name="GLTF_created_0">
//                             <primitive
//                               object={nodes.GLTF_created_0_rootJoint}
//                             />
//                             <skinnedMesh
//                               name="Object_233"
//                               geometry={nodes.Object_233.geometry}
//                               material={materials.material_0}
//                               skeleton={nodes.Object_233.skeleton}
//                             />
//                             <group name="Object_228_228_correction">
//                               <group name="Object_228_228" />
//                             </group>
//                           </group>
//                         </group>
//                       </group>
//                     </group>
//                   </group>
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/dragon_flying.glb");
