import {useRef, useEffect} from 'react'
import pugScene from '../assets/3d/cute_pug.glb';
import { useAnimations, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Pug = () => {
    const { scene, animations } = useGLTF(pugScene);
    const pugRef = useRef();
    const { actions } = useAnimations(animations, pugRef);

    // useEffect(() => {
    //   actions["Take 001"].play();
    // }, []);

    useFrame(({clock, camera}) => {
      pugRef.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 2

      if(pugRef.current.position.x > camera.position.x + 10){
        pugRef.current.rotation.y = Math.PI;
      } else if(pugRef.current.position.x < camera.position.x - 10) {
        pugRef.current.rotation.y = 0;
      }
      if(pugRef.current.rotation.y === 0){
        pugRef.current.position.x += 0.01;
        pugRef.current.position.z -= 0.01;
      }else {
        pugRef.current.position.x -= 0.01;
        pugRef.current.position.z += 0.01;
      }
    })
  return (
    <mesh position={[-5, 2, 1]} scale={[0.003, 0.003, 0.003]} ref={pugRef}>
        <primitive object={scene}/>
    </mesh>
  )
}
export default Pug
// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: ordenmoria (https://sketchfab.com/ordenmoria)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/cute-pug-f9c8c8ff399948d2bd0203642e4e23a1
// Title: Cute pug
// */

// import React, { useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";

// export function Model(props) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF("/cute_pug.glb");
//   const { actions } = useAnimations(animations, group);
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group
//           name="Sketchfab_model"
//           position={[92.304, -175.954, 75.803]}
//           rotation={[-Math.PI / 2, 0, 0]}
//         >
//           <group name="06fbx" rotation={[Math.PI / 2, 0, 0]}>
//             <group name="Object_2">
//               <group name="RootNode">
//                 <group
//                   name="NurbsPath"
//                   rotation={[-Math.PI / 2, 0, 2.266]}
//                   scale={229.826}
//                 >
//                   <mesh
//                     name="NurbsPath_Texturas_cuerpo_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.NurbsPath_Texturas_cuerpo_0.geometry}
//                     material={materials.Texturas_cuerpo}
//                   />
//                   <group
//                     name="Cube004"
//                     position={[-3.505, -0.007, 1.054]}
//                     rotation={[-2.431, -0.085, -1.494]}
//                     scale={0.113}
//                   >
//                     <mesh
//                       name="Cube004_Texturas_boca_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Cube004_Texturas_boca_0.geometry}
//                       material={materials.Texturas_boca}
//                     />
//                   </group>
//                   <group
//                     name="Cube001"
//                     position={[-3.604, 0.324, 1.179]}
//                     rotation={[0.738, -0.085, -1.494]}
//                     scale={0.284}
//                   >
//                     <mesh
//                       name="Cube001_Texturas_boca_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Cube001_Texturas_boca_0.geometry}
//                       material={materials.Texturas_boca}
//                     />
//                     <group
//                       name="Cube"
//                       position={[0.02, -0.406, 1.949]}
//                       rotation={[-0.868, -0.528, -0.537]}
//                       scale={0.499}
//                     >
//                       <mesh
//                         name="Cube_Texturas_boca_0"
//                         castShadow
//                         receiveShadow
//                         geometry={nodes.Cube_Texturas_boca_0.geometry}
//                         material={materials.Texturas_boca}
//                       />
//                     </group>
//                     <group
//                       name="Cube002"
//                       position={[2.48, -0.972, -0.776]}
//                       rotation={[-0.59, -0.707, -0.535]}
//                       scale={[0.552, 0.552, 0.99]}
//                     >
//                       <mesh
//                         name="Cube002_Texturas_lengua_0"
//                         castShadow
//                         receiveShadow
//                         geometry={nodes.Cube002_Texturas_lengua_0.geometry}
//                         material={materials.Texturas_lengua}
//                       />
//                     </group>
//                   </group>
//                   <group
//                     name="Sphere001"
//                     position={[-3.292, -0.914, 1.998]}
//                     rotation={[-0.088, 0.074, 2.443]}
//                     scale={0.753}
//                   >
//                     <mesh
//                       name="Sphere001_Texturas_ojos_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Sphere001_Texturas_ojos_0.geometry}
//                       material={materials.Texturas_ojos}
//                     />
//                   </group>
//                   <group
//                     name="Cube003"
//                     position={[-1.425, 2.341, 3.079]}
//                     rotation={[0.694, 0.03, -2.986]}
//                     scale={[0.598, 0.346, 0.415]}
//                   >
//                     <mesh
//                       name="Cube003_Texturas_boca_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Cube003_Texturas_boca_0.geometry}
//                       material={materials.Texturas_boca}
//                     />
//                   </group>
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/cute_pug.glb");
