/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SirSquiggles (https://sketchfab.com/sirsquiggles)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sanrio-tuxedo-sam-3d-model-2c715aaf07824106a0a70c4e48626d17
Title: Sanrio Tuxedo Sam 3D Model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/sanrio_tuxedo_sam_3d_model.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Sailor_Hat_White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Sam_Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.pink}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.yellow}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/sanrio_tuxedo_sam_3d_model.glb");
